# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- bash: |
 

    curl --insecure -H "Content-Type: application/json" -X POST -u xRayUser:Staples123 --data @/home/devuser/myagent/_work/4/s/target/cucumber-report/runwebat/cucumber.json  https://jira.services.staples-solutions.com/rest/raven/1.0/import/execution/cucumber